__include__: [
  '../dfine/dfine_hgnetv2_n_custom.yml',
  '../dataset/visdrone_detection.yml',
  '../base/deim.yml'
]

print_freq: 20
output_dir: ./outputs/deim_hgnetv2_n_visdrone_pointonly

num_classes: 10
remap_mscoco_category: False

use_ema: True

find_unused_parameters: True

PointSupervision:
  enabled: True
  cost_point: 1.0
  cost_class: 2.0
  cost_prior: 0.25
  score_thresh: 0.1
  max_l1_dist: 0.25
  snap_center: True
  keep_all_points: False
  DensityLimit:
    enabled: True
    knn_k: 1
    density_margin_factor: 1.2
    class_margin_factors: {3: 2.0, 4: 2.0, 9: 2.0, 5: 2.5, 8: 2.5}
    global_max_wh_px: 256.0
    global_min_wh_px: 6.0
    use_input_hw: True
  FeatureGrowth:
    enabled: True
    feature_level: 1
    feature_key: pseudo_feat
    tau: 0.65
    min_mask_px: 6
  DSPE:
    enabled: True
    base_size: 640
    bag_size: 16
    explore_ratio: 0.5
    explore_wh_px: [2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 96, 128, 160, 192, 256]
    update_top_frac: 0.1
    update_beta: 0.001
    update_score_thresh: 0.2
    update_max_dist_px: 160
    update_stab_thresh: 0.6
    wh_override: False
    pseudo_prior_mix: 0.0
    pseudo_prior_mix_schedule: ~
    wh_select_k: 32
    bag_aspect_ratios: [0.5, 1.0, 2.0]
    bag_wh_weight: 1.0
    pseudo_min_wh_px: 6
    pseudo_max_wh_px: 256
    init_mean_wh_px: [20, 20]
    init_std_wh_px: [20, 20]
    min_std_px: [0.35, 0.35]
    large_box_area_ratio_thresh: 2.0
    large_box_area_penalty: 5.0
    update_max_area_ratio: 10.0
    log_interval: 200

val_dataloader:
  dataset:
    img_folder: /home/pc/gxy/dataset/dataset_visdrone/VisDrone2019-DET-val/images
    ann_file: /home/pc/gxy/dataset/dataset_visdrone/VisDrone2019-DET-val/annotations/val.json

model: DEIM_MG

DEIM_MG:
  yaml_path: configs/cfg/dfine-n.yaml

DEIMCriterion:
  weight_dict: {loss_mal: 1, loss_bbox: 0, loss_giou: 0, loss_fgl: 0.15, loss_ddf: 1.5, loss_points_mil_reg: 5}
  losses: ['mal', 'points_mil_reg', 'local']

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# Increase to search for the optimal ema
epoches: 160 # 148 + 12

## Our LR-Scheduler
flat_epoch: 78    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 12
lr_gamma: 1.0

## Our DataAug
train_dataloader:
  dataset:
    img_folder: /home/pc/gxy/dataset/dataset_visdrone/VisDrone2019-DET-train/images
    ann_file: /home/pc/gxy/dataset/dataset_visdrone/deim_point_only_6px/annotations/instances_train.json
    transforms:
      policy:
        epoch: [4, 78, 148]   # list
  collate_fn:
    mixup_epochs: [4, 78]
    stop_epoch: 148
    base_size_repeat: ~
