__include__: [
  '../runtime.yml',
]

task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 4
# num_classes: 4
remap_mscoco_category: False

print_freq: 2000
output_dir: ./outputs/deim_hgnetv2_x_mm
checkpoint_freq: 4
plot_train_batch_freq: 12

sync_bn: True
find_unused_parameters: True
verbose_type: 'origin'

use_amp: True
scaler:
  type: GradScaler
  enabled: True

use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
  start: 0

cache_imgsz: 960
ram_cache: False

yolo_metrice: True

epoches: 58
clip_max_norm: 0.1

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.000125

lr_scheduler:
  type: MultiStepLR
  milestones: [500]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 500

model: DEIM_MG
criterion: DEIMCriterion
postprocessor: PostProcessor

use_focal_loss: True
eval_spatial_size: [640, 640]

lrsheduler: flatcosine
lr_gamma: 0.5
warmup_iter: 2000
flat_epoch: 29
no_aug_epoch: 8

PostProcessor:
  num_top_queries: 300

DEIM_MG:
  yaml_path: configs/mutilmodality/yaml/dfine-x-mm.yaml
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

train_dataloader:
  type: DataLoader
  dataset:
    type: MultimodalCocoDetection
    img_folder: /root/code/project/DEIM-MutilModel-Dataset/FLIR_v1_align/converted/rgb/train
    npy_folder: /root/code/project/DEIM-MutilModel-Dataset/FLIR_v1_align/converted/preview_npy/train
    ann_file: /root/code/project/DEIM-MutilModel-Dataset/FLIR_v1_align/converted/annotations/instances_train_rgb.json
    return_masks: False
    npy_size_mismatch: error
    transforms:
      type: MultimodalCompose
      ops:
        - {type: MultimodalMosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5], probability: 1.0, fill_value: 0, use_cache: False, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: NormalizeNPYMinMax}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: [4, 29, 50]
        ops: ['MultimodalMosaic', 'RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
      mosaic_prob: 0.5
  collate_fn:
    type: BatchMultimodalCollateFunction
    base_size: 640
    stop_epoch: 50
    mixup_prob: 0.5
    mixup_epochs: [4, 29]
  shuffle: True
  num_workers: 4
  drop_last: True
  pin_memory: True
  total_batch_size: 4

val_dataloader:
  type: DataLoader
  dataset:
    type: MultimodalCocoDetection
    img_folder: /root/code/project/DEIM-MutilModel-Dataset/FLIR_v1_align/converted/rgb/val
    npy_folder: /root/code/project/DEIM-MutilModel-Dataset/FLIR_v1_align/converted/preview_npy/val
    ann_file: /root/code/project/DEIM-MutilModel-Dataset/FLIR_v1_align/converted/annotations/instances_val_rgb.json
    return_masks: False
    npy_size_mismatch: error
    transforms:
      type: MultimodalCompose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: NormalizeNPYMinMax}
  collate_fn:
    type: BatchMultimodalCollateFunction
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: True
  total_batch_size: 4

DEIMCriterion:
  weight_dict: {loss_mal: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5}
  losses: ['mal', 'boxes', 'local']
  alpha: 0.75
  gamma: 1.5
  reg_max: 32
  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0
