backbone:
  # [from, module, args]
  - [-1, ConvNeXt_Tiny, {"pretrained": "dinov3_convnext_tiny_pretrain_lvd1689m-21b726bb.pth", "return_idx":[0, 1, 2, 3]}] # 0
  - [0, GetIndexOutput, [1]] # 1-P3
  - [0, GetIndexOutput, [2]] # 2-P4
  - [0, GetIndexOutput, [3]] # 3-P5

encoder:
  - [1, ConvNormLayer_fuse, [256, 1, 1]] # 4-P3/8
  - [2, ConvNormLayer_fuse, [256, 1, 1]] # 5-P4/16
  - [3, ConvNormLayer_fuse, [256, 1, 1]] # 6-P5/32

  - [-1, TransformerEncoderBlock, [8, 1024, 0.1, "relu", 10000, False]] # 7-P5/32

  - [-1, ConvNormLayer_fuse, [256, 1, 1]] # 8
  - [-1, nn.Upsample, [None, 2, "nearest"]] # 9
  - [[-1, 5], Concat, []] # 10-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 128, 3, False, 'silu']] # 11-P4/16

  - [-1, ConvNormLayer_fuse, [256, 1, 1]] # 12
  - [-1, nn.Upsample, [None, 2, "nearest"]] # 13
  - [[-1, 4], Concat, []] # 14-P3/8
  - [-1, RepNCSPELAN4, [256, 512, 128, 3, False, 'silu']] # 15-P3/8

  - [-1, SCDown, [256, 3, 2, 'silu']] # 16-P4/16
  - [[-1, 12], Concat, []] # 17-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 128, 3, False, 'silu']] # 18-P4/16

  - [-1, SCDown, [256, 3, 2, 'silu']] # 19-P5/32
  - [[-1, 8], Concat, []] # 20-P5/32
  - [-1, RepNCSPELAN4, [256, 512, 128, 3, False, 'silu']] # 21-P5/32

decoder:
  - [[15, 18, 21], DFINETransformer, {"feat_strides":[8, 16, 32], "hidden_dim": 256, "num_levels": 3, "num_layers": 6, "num_points": [3, 6, 3], "dim_feedforward": 1024}]
