__include__: [
  './deim_hgnetv2_n_point_only_smallobj_all_gated_v2.yml'
]

output_dir: outputs/nwpu_vhr10_point_only_smallobj_all_gated_v2_hgpre_balanced

HGNetv2:
  pretrained: True
  local_model_dir: ./weight/hgnetv2/

PointSupDEIMCriterionScaleAdaptiveInitScoreThreshSchedule:
  pseudo_box:
    # 1. 恢复极小的硬性下限，防止大框霸权
    prior_wh: 0.03
    min_wh: 0.005
    # 2. 上限依然放开，允许桥梁生长
    max_wh: 0.85
    
    # 🌟【关键修复 A】加大过度扩张惩罚！如果框包住了没用的背景，重罚！
    density_recall_penalty: 1.5
    density_precision_penalty: 1.35  # 原来是 1.1，现大幅提高，逼迫伪框收紧

    # 3. 预热期缩短，防止在无语义引导下几何无脑扩张
    class_agnostic_warmup_epochs: 4
    
    # 4. 生长速率回归稳健
    max_scale_up: 1.5
    max_scale_down: 0.2

  # 🌟【关键修复 B】开局种子必须极小！迎合 90% 的小目标
  adaptive_scale: 0.10   # 从 0.35 降维打击到 0.10
  
  # 5. 阈值平滑调度
  score_thresh_start: 0.55
  score_thresh_end: 0.30
  score_thresh_end_epoch: 60

train_dataloader:
  dataset:
    prior_wh: 0.03
    min_wh: 0.005
    max_wh: 0.85