__include__: [
  './deim_hgnetv2_n_point_only_smallobj_all_gated_v2_ptteacher_v1.yml'
]

epoches: 2
flat_epoch: 1
no_aug_epoch: 1

output_dir: outputs/nwpu_vhr10_point_only_smallobj_all_gated_v2_ptteacher_smoke
