__include__: [
  './deim_hgnetv2_n_point_only.yml'
]

output_dir: outputs/nwpu_vhr10_point_only_pg_crop

train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: PointGuidedCrop, p: 0.8, min_crop_size: 128, max_crop_size: 640, object_scale: 4.0, pick_smallest: True}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'PointGuidedCrop']

