__include__: [
  './deim_hgnetv2_n_point_only_smallobj_all_gated_v2_hgpre_balanced_v4.yml'
]

output_dir: outputs/nwpu_vhr10_point_only_smallobj_all_gated_v2_hgpre_balanced_v5

PointSupDEIMCriterionScaleAdaptiveInitScoreThreshSchedule:
  pseudo_box:
    score_topk: 5
    score_topk_begin_epoch: 0
    score_topk_end_epoch: 3
