__include__:
- ../deim/deim_hgnetv2_n_custom.yml
output_dir: ./outputs/afss_training/deim_hgnetv2_n_custom_afss
train_dataloader:
  dataset:
    type: AFSSDataset
    dataset:
      type: CocoDetection
      img_folder: /home/hjj/Desktop/project/DEIM/dataset/train/images
      ann_file: /home/hjj/Desktop/project/DEIM/dataset/train/annotations/data.json
      return_masks: false
      transforms:
        type: Compose
        ops:
        - type: Mosaic
          output_size: 320
          rotation_range: 10
          translation_range:
          - 0.1
          - 0.1
          scaling_range:
          - 0.5
          - 1.5
          probability: 1.0
          fill_value: 0
          use_cache: false
          max_cached_images: 50
          random_pop: true
        - type: RandomPhotometricDistort
          p: 0.5
        - type: RandomZoomOut
          fill: 0
        - type: RandomIoUCrop
          p: 0.8
        - type: SanitizeBoundingBoxes
          min_size: 1
        - type: RandomHorizontalFlip
        - type: Resize
          size:
          - 640
          - 640
        - type: SanitizeBoundingBoxes
          min_size: 1
        - type: ConvertPILImage
          dtype: float32
          scale: true
        - type: ConvertBoxes
          fmt: cxcywh
          normalize: true
        policy:
          name: stop_epoch
          epoch:
          - 4
          - 78
          - 148
          ops:
          - Mosaic
          - RandomPhotometricDistort
          - RandomZoomOut
          - RandomIoUCrop
        mosaic_prob: 0.5
afss_update_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/hjj/Desktop/project/DEIM/dataset/train/images
    ann_file: /home/hjj/Desktop/project/DEIM/dataset/train/annotations/data.json
    return_masks: false
    transforms:
      type: Compose
      ops:
      - type: Resize
        size:
        - 640
        - 640
      - type: ConvertPILImage
        dtype: float32
        scale: true
  shuffle: false
  num_workers: 4
  drop_last: false
  pin_memory: true
  collate_fn:
    type: BatchImageCollateFunction
  total_batch_size: 8
AFSS:
  enabled: true
  dump_refresh_json: false
  easy_threshold: 0.85
  moderate_threshold: 0.55
  easy_ratio: 0.02
  moderate_ratio: 0.4
  easy_review_gap: 10
  moderate_gap: 3
  update_interval: 5
  warmup_epochs: 5
  review_force_cap_ratio: 0.5
  iou_threshold: 0.5
  conf_threshold: 0.25
  random_seed: 0
